FROM php:8.2-apache

WORKDIR /home

RUN apt-get update 
RUN apt-get install -y \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    libzip-dev \
    mariadb-client \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath zip -j$(nproc) gd \
    && a2enmod rewrite

RUN docker-php-ext-install mysqli

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . .

RUN composer install

RUN php artisan key:generate

RUN a2enmod rewrite

EXPOSE 80

CMD ["apache2-foreground"]
